server:
  provider: huaweicloud
  region: cn-east-3
  hostname: ecs-example
  os: centos7

resources:
  egresses:
    - id: main
      bind_ip: 192.168.0.10
      expected_public_ip: 122.9.78.47
      kind: primary
      note: 主IP出口

    - id: vip1
      bind_ip: 192.168.0.11
      expected_public_ip: 116.63.211.118
      kind: vip
      note: 虚拟IP 1

    - id: vip2
      bind_ip: 192.168.0.12
      expected_public_ip: 116.63.208.139
      kind: vip
      note: 虚拟IP 2

    - id: nic1
      bind_ip: 192.168.1.250
      expected_public_ip: ""
      kind: secondary_nic
      note: 辅助弹性网卡 1

proxies:
  - name: proxy01
    resource_id: main
    listen_ip: 192.168.0.10
    port: 19001
    username: vip1
    password: 123456
    account_label: vip1

  - name: proxy02
    resource_id: vip1
    listen_ip: 192.168.0.11
    port: 19002
    username: vip2
    password: 123456
    account_label: vip2

  - name: proxy03
    resource_id: vip2
    listen_ip: 192.168.0.12
    port: 19003
    username: vip3
    password: 123456
    account_label: vip3

  - name: proxy04
    resource_id: nic1
    listen_ip: 192.168.1.250
    port: 19004
    username: vip4
    password: 123456
    account_label: vip4
