#!/usr/bin/env python3
import argparse
import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Missing dependency: pyyaml\nInstall with: python3 -m pip install pyyaml", file=sys.stderr)
    raise


SERVICE_TEMPLATE = """[Unit]
Description=Xray Proxy Service (generated by xhs-proxy-rebuilder)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/xray run -c {config_path}
Restart=always
RestartSec=5s
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
"""


def load_inventory(path: Path) -> dict:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("Inventory must be a YAML mapping")
    proxies = data.get("proxies")
    if not isinstance(proxies, list) or not proxies:
        raise ValueError("Inventory must contain a non-empty 'proxies' list")
    return normalize_inventory(data)


def normalize_inventory(data: dict) -> dict:
    resources = data.get("resources", {})
    egresses = resources.get("egresses") if isinstance(resources, dict) else None
    if isinstance(egresses, list) and egresses:
        egress_map = {}
        for item in egresses:
            if not item.get("id") or not item.get("bind_ip"):
                raise ValueError("Each egress resource must have 'id' and 'bind_ip'")
            egress_map[item["id"]] = item

        normalized = []
        for idx, proxy in enumerate(data["proxies"], start=1):
            resource_id = proxy.get("resource_id")
            if not resource_id:
                raise ValueError(f"Proxy #{idx} missing resource_id in V2 inventory")
            if resource_id not in egress_map:
                raise ValueError(f"Proxy #{idx} references unknown resource_id: {resource_id}")
            resource = egress_map[resource_id]
            merged = dict(proxy)
            merged["send_through"] = resource["bind_ip"]
            merged["expected_public_ip"] = resource.get("expected_public_ip", "")
            merged["resource_kind"] = resource.get("kind", "")
            merged["resource_note"] = resource.get("note", "")
            normalized.append(merged)

        output = dict(data)
        output["proxies"] = normalized
        return output

    return data


def validate_proxy(proxy: dict, index: int) -> None:
    required = [
        "name",
        "listen_ip",
        "port",
        "username",
        "password",
        "send_through",
        "account_label",
    ]
    missing = [key for key in required if not proxy.get(key) and proxy.get(key) != 0]
    if missing:
        raise ValueError(f"Proxy #{index} missing fields: {', '.join(missing)}")
    port = proxy["port"]
    if not isinstance(port, int) or not (1 <= port <= 65535):
        raise ValueError(f"Proxy #{index} has invalid port: {port}")


def build_xray_config(inventory: dict) -> dict:
    inbounds = []
    outbounds = []
    rules = []

    for idx, proxy in enumerate(inventory["proxies"], start=1):
        validate_proxy(proxy, idx)
        tag = proxy["name"]
        inbound_tag = f"in-{tag}"
        outbound_tag = f"out-{tag}"

        inbounds.append(
            {
                "listen": proxy["listen_ip"],
                "port": proxy["port"],
                "protocol": "socks",
                "tag": inbound_tag,
                "settings": {
                    "auth": "password",
                    "udp": True,
                    "ip": proxy["listen_ip"],
                    "accounts": [
                        {
                            "user": proxy["username"],
                            "pass": str(proxy["password"]),
                        }
                    ],
                },
                "sniffing": {
                    "enabled": False,
                },
            }
        )

        outbounds.append(
            {
                "protocol": "freedom",
                "tag": outbound_tag,
                "sendThrough": proxy["send_through"],
                "settings": {},
            }
        )

        rules.append(
            {
                "type": "field",
                "inboundTag": [inbound_tag],
                "outboundTag": outbound_tag,
            }
        )

    outbounds.append({"protocol": "blackhole", "tag": "blocked", "settings": {}})

    return {
        "log": {"loglevel": "warning"},
        "inbounds": inbounds,
        "outbounds": outbounds,
        "routing": {"domainStrategy": "AsIs", "rules": rules},
    }


def write_exports(inventory: dict, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    proxies = inventory["proxies"]

    proxies_json = output_dir / "proxies.json"
    proxies_csv = output_dir / "proxies.csv"
    proxies_txt = output_dir / "proxies.txt"

    proxies_json.write_text(
        json.dumps(proxies, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    with proxies_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "name",
                "listen_ip",
                "port",
                "username",
                "password",
                "send_through",
                "expected_public_ip",
                "account_label",
                "resource_kind",
                "resource_note",
            ],
            extrasaction="ignore",
        )
        writer.writeheader()
        writer.writerows(proxies)

    lines = []
    for p in proxies:
        resource_extra = ""
        if p.get("resource_kind") or p.get("resource_note"):
            resource_extra = f" kind={p.get('resource_kind', '')} note={p.get('resource_note', '')}"
        lines.append(
            f"{p['name']} {p['listen_ip']}:{p['port']} {p['username']} {p['password']} sendThrough={p['send_through']} expected_public_ip={p.get('expected_public_ip', '')} label={p['account_label']}{resource_extra}"
        )
    proxies_txt.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_systemd_unit(output_dir: Path, config_path: Path) -> Path:
    service_path = output_dir / "xray.service"
    service_path.write_text(
        SERVICE_TEMPLATE.format(config_path=config_path),
        encoding="utf-8",
    )
    return service_path


def write_resource_plan(inventory: dict, output_dir: Path) -> Path:
    resources = inventory.get("resources", {}) if isinstance(inventory, dict) else {}
    egresses = resources.get("egresses", []) if isinstance(resources, dict) else []
    resource_path = output_dir / "resource-plan.json"
    resource_path.write_text(
        json.dumps(egresses, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return resource_path


def write_install_notes(output_dir: Path, config_path: Path, service_path: Path) -> None:
    notes = f"""# Install Notes

## Suggested target paths
- Xray config: /etc/xray/config.json
- Systemd service: /etc/systemd/system/xray.service

## Copy generated files
```bash
sudo mkdir -p /etc/xray
sudo cp {config_path} /etc/xray/config.json
sudo cp {service_path} /etc/systemd/system/xray.service
```

## Reload and enable service
```bash
sudo systemctl daemon-reload
sudo systemctl enable xray
sudo systemctl restart xray
sudo systemctl status xray --no-pager
```
"""
    (output_dir / "INSTALL.md").write_text(notes, encoding="utf-8")


def write_manifest(output_dir: Path, inventory_path: Path, profile_path: Path | None, inventory: dict) -> None:
    proxies = inventory.get("proxies", [])
    resource_kinds = sorted({p.get("resource_kind", "") for p in proxies if p.get("resource_kind")})
    sample_accounts = [
        {
            "name": p.get("name"),
            "listen": f"{p.get('listen_ip')}:{p.get('port')}",
            "username": p.get("username"),
            "resource_kind": p.get("resource_kind", ""),
        }
        for p in proxies[:5]
    ]
    manifest = {
        "generated_at_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "inventory": str(inventory_path),
        "profile": str(profile_path) if profile_path else None,
        "proxy_count": len(proxies),
        "resource_kinds": resource_kinds,
        "sample_accounts": sample_accounts,
    }
    (output_dir / "build-manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    lines = [
        "# Build Manifest V1",
        "",
        f"- Generated at (UTC): `{manifest['generated_at_utc']}`",
        f"- Inventory: `{manifest['inventory']}`",
        f"- Profile: `{manifest['profile']}`" if manifest["profile"] else "- Profile: 未记录",
        f"- Proxy count: `{manifest['proxy_count']}`",
        f"- Resource kinds: `{', '.join(resource_kinds)}`" if resource_kinds else "- Resource kinds: 未记录",
        "",
        "## Sample Accounts",
        "",
    ]
    for item in sample_accounts:
        lines.append(
            f"- {item['name']} -> {item['listen']} user={item['username']} kind={item['resource_kind']}"
        )
    (output_dir / "BUILD.README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Xray config from HuaweiCloud inventory")
    parser.add_argument(
        "inventory",
        nargs="?",
        default="inventory/huaweicloud-sample.yaml",
        help="Path to inventory YAML",
    )
    parser.add_argument(
        "--output-dir",
        default="generated",
        help="Directory to place generated files",
    )
    parser.add_argument(
        "--xray-config-name",
        default="xray-config.json",
        help="Generated xray config filename",
    )
    parser.add_argument(
        "--profile",
        help="Profile YAML used for this build",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress normal summary output",
    )
    args = parser.parse_args()

    base_dir = Path(__file__).resolve().parents[1]
    inventory_path = (base_dir / args.inventory).resolve() if not Path(args.inventory).is_absolute() else Path(args.inventory)
    output_dir = (base_dir / args.output_dir).resolve() if not Path(args.output_dir).is_absolute() else Path(args.output_dir)
    profile_path = None
    if args.profile:
        profile_path = (base_dir / args.profile).resolve() if not Path(args.profile).is_absolute() else Path(args.profile)

    inventory = load_inventory(inventory_path)
    xray_config = build_xray_config(inventory)

    output_dir.mkdir(parents=True, exist_ok=True)
    xray_config_path = output_dir / args.xray_config_name
    xray_config_path.write_text(json.dumps(xray_config, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    write_exports(inventory, output_dir)
    resource_plan_path = write_resource_plan(inventory, output_dir)
    service_path = write_systemd_unit(output_dir, Path("/etc/xray/config.json"))
    write_install_notes(output_dir, xray_config_path, service_path)
    write_manifest(output_dir, inventory_path, profile_path, inventory)

    if not args.quiet:
        print(f"Inventory: {inventory_path}")
        if profile_path:
            print(f"Profile: {profile_path}")
        print(f"Generated xray config: {xray_config_path}")
        print(f"Generated resource plan: {resource_plan_path}")
        print(f"Generated systemd service: {service_path}")
        print(f"Generated manifest: {output_dir / 'build-manifest.json'}")
        print(f"Generated exports in: {output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
